// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixcgauiwwopvzbifnyit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Y2dhdWl3d29wdnpiaWZueWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTcxNTUsImV4cCI6MjA4Nzc3MzE1NX0.zYSFs1u9iJATfSL5qb-mQrQ957m7kMI2Obz9fSKgCYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});